%YAML:1.0
---
image_width: 1280
image_height: 720
camera_name: narrow_stereo

camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [672.303608,   .0    , 628.627112,
         0.     , 666.205653, 308.765712,
         0.     ,   0.     ,   1.     ]

distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [-0.315333, 0.084113, 0.001439, 0.002614, 0.000000]

rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]

projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [490.956879, 0.000000, 637.221868, 0.000000,
        0.000000, 591.307556, 296.656137,   0.     ,
         0.     ,   0.     ,   1.     ,   0.     ]